version: '3'

services:
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver"
    container_name: myapp
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
